global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'habit-service'
    static_configs:
      - targets: ['habit-service:8001']
    metrics_path: '/metrics'

  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:8002']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8003']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8004']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
